version: '3.9'

services:
  postgresql:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_POSTGRES_PASSWORD=supergene # root password
      - POSTGRESQL_USERNAME=supergene
      - POSTGRESQL_PASSWORD=supergene

    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fenrir -d fenrir" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6383:6379"
    volumes:
      - redis:/data
    command: redis-server --notify-keyspace-events KEA
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis:
  postgres_data:
  postgres_data_temp:

